language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
script:
  - yarn build
  - yarn test:ci
  - yarn lint
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
