language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn test:ci && yarn build && yarn lint
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
