name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
      #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Install asdf plugins and tools
          uses: asdf-vm/actions/install@v1

        - name: Get pnpm store directory
          id: pnpm-cache
          run: |
            echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
        - name: Setup pnpm cache
          uses: actions/cache@v3
          with:
            path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-pnpm-store-

        - name: Install Dependencies
          run: pnpm install

        - name: Build
          run: pnpm build

        - name: Lint
          run: pnpm lint

        - name: Test
          run: pnpm test

        - name: Upload @iniz/core coverage
          uses: codecov/codecov-action@v2
          with:
            files: ./packages/core/coverage/coverage-final.json
            flags: core
            token: ${{ secrets.CODECOV_TOKEN }}

        - name: Upload @iniz/react coverage
          uses: codecov/codecov-action@v2
          with:
            files: ./packages/react/coverage/coverage-final.json
            flags: react
            token: ${{ secrets.CODECOV_TOKEN }}
